packages:
  - '.'

# pnpm v10 blocks dependency install scripts by default.
# This allowlist enables the minimal set of packages that need build scripts for this app.
onlyBuiltDependencies:
  - '@emberai/agent-node'
  - '@pnpm/exe'
  - bufferutil
  - esbuild
  - keccak
  - utf-8-validate
