name: 📚 Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[DOCS] "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Vibekit documentation! Clear docs are essential for developer experience.

  - type: dropdown
    id: doc-type
    attributes:
      label: 📂 Documentation Type
      description: What type of documentation needs attention?
      options:
        - Setup/Installation Guide
        - API Documentation
        - Agent Template Guide
        - MCP Integration Guide
        - Code Examples/Tutorials
        - Architecture/Design Docs
        - Troubleshooting Guide
        - Contributing Guidelines
        - README files
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: 🎯 Issue Type
      description: What's wrong with the documentation?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear/confusing explanation
        - Broken links or references
        - Missing code examples
        - Poor organization/structure
        - Incomplete information
        - Inconsistent formatting
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: 📍 Documentation Location
      description: Where is this documentation located (or where should it be)?
      placeholder: |
        File path: typescript/templates/ember-agent/README.md
        URL: https://github.com/EmberAGI/arbitrum-vibekit/...
        Section: "Getting Started" section in main README
        New location needed: docs/guides/protocol-integration.md
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: 📋 Current State
      description: Describe what currently exists (if anything)
      placeholder: |
        Current documentation says...
        The current example shows...
        There's no documentation for...
        The link goes to...

  - type: textarea
    id: expected-state
    attributes:
      label: ✅ Desired State
      description: What should the documentation include or explain?
      placeholder: |
        Should clearly explain how to...
        Needs step-by-step guide for...
        Should include examples of...
        Link should point to...
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: 👥 Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - New developers getting started
        - Experienced developers integrating protocols
        - DeFi users/traders
        - Contributors to the project
        - System administrators/DevOps
        - All users
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: 🎯 User Impact
      description: How does this documentation issue affect users?
      placeholder: |
        Users get stuck when trying to...
        This prevents developers from...
        Makes it hard to understand...
        Causes confusion about...
    validations:
      required: true

  - type: textarea
    id: related-code
    attributes:
      label: 🔗 Related Code/Features
      description: What code, features, or components should this documentation cover?
      placeholder: |
        Related to the swap functionality in...
        Covers the MCP server implementation...
        Should document the agent lifecycle...
        Explains the hook system in...

  - type: textarea
    id: examples-needed
    attributes:
      label: 💡 Examples Needed
      description: What specific examples or code snippets would be helpful?
      placeholder: |
        Example of setting up environment variables
        Code snippet showing how to create a custom agent
        Step-by-step protocol integration example
        Configuration file examples

  - type: dropdown
    id: priority
    attributes:
      label: 📈 Priority
      description: How critical is this documentation fix?
      options:
        - Critical - Blocks new users from getting started
        - High - Significantly impacts developer experience
        - Medium - Improves clarity and usability
        - Low - Minor improvement
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution Interest
      options:
        - label: I'm willing to write/improve this documentation
        - label: I can provide examples or code snippets
        - label: I can review and test the documentation
        - label: I can help with technical writing

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: Any other relevant information, screenshots, or context
      placeholder: |
        Screenshots of confusing UI...
        Links to helpful references...
        Related discussions or issues...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      options:
        - label: I have searched existing issues for similar documentation problems
          required: true
        - label: I have clearly identified the documentation location
          required: true
        - label: I have described what needs to be fixed or added
          required: true
        - label: I have explained how this impacts users
          required: true