import type { Metadata } from 'next';

import { CopilotKit } from '@copilotkit/react-core';
import './globals.css';
import '@copilotkit/react-ui/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const AGENT_NAME = 'agent-clmm';

  return (
    <html lang="en">
      <body className={'antialiased'}>
        {/* Pass `threadId` to manage separate threads manually or keep it undefined to auto-generate a new thread and ID*/}
        <CopilotKit runtimeUrl="/api/copilotkit" agent={AGENT_NAME} threadId={undefined}>
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
